### PR TITLE
Add FR EN translation for charge_mode

### LINKED ISSUE #81: Add translations for "SCHEDULE_MODE"
For the calendar, is it possible to translate "SCHEDULE_MODE" by "Activated", "Activé" in french, and "ALWAYS_CHARGING" by "Deactivated", "Désactivé" in french?

Capture

_Originally posted by @JeedHome44 in https://github.com/hacf-fr/hassRenaultZE/issues/41#issuecomment-739443737_

### PR DESCRIPTION
**Pull request by JeedHome44**
Close #81

### CODE REVIEW

**Comment by epenet** [comment]
You need to rebase your branch.

**Comment by JeedHome44** [comment]
How please? I don't know.

**Comment by epenet** [comment]
I do not have permission to update your branch. Maybe it is best if you delete your branch/fork and recreate it

**Comment by epenet** [comment]
Replaced by #96

**Pull request closed without merging**
