### PR TITLE
Bump renault_api from 0.0.2 to 0.0.3

### LINKED ISSUE #87: Charge_mode on/off fails
Don't work:
Charge_mode on: KO > need lowercase
Charge_mode off: KO > need lowercase
Hvac off: KO > never work

Work:
Hvac on: OK
Calendar_set: OK > Activ Cal
Charge_go: OK > Deactiv Cal

I think the problem with charge_mode is the upper case letters in the script.  if I put SCHEDULE_MODE or ALWAYS_CHARGING in lowercase, the script does not work.  But I think we have to send lowercase to Renault.  can you fix this problem?

_Originally posted by @JeedHome44 in https://github.com/hacf-fr/hassRenaultZE/issues/83#issuecomment-739551495_

### PR DESCRIPTION
**Pull request by JeedHome44**
Update renault_api 0.0.3
Close #87

### CODE REVIEW

**Comment by JeedHome44** [comment]
Close #87

**Comment by epenet** [comment]
Please edit the top comment to add the closes statement.

**Comment by JeedHome44** [comment]
like that?

**Comment by epenet** [comment]
One more thing for future: create separate branches for separate PR...

**Pull request merged**
