### PR TITLE
Add checks for endpoint support and contract requirements

### PR DESCRIPTION
**Pull request by epenet**
Relates to #51

### CODE REVIEW

**Comment by epenet** [comment]
@oncleben31 this makes use of your contract implementation from https://github.com/hacf-fr/renault-api/pull/145

Hopefully it should remove the ERROR and replace it with a WARNING.
Do you think this is OK? or should we go one step lower and replace it with INFO?

**Comment by oncleben31** [comment]
From my experience it's more an INFO. But I understood that it could be a way to notify an expired contract not renewed by error. In this second case it is more a warning.
What do you think about INFO if the contract is missing and WARNING if the contract is expired ?

**Comment by epenet** [comment]
INFO on "support_endpoint"
WARNING on "has_contract"

**Comment by epenet** [comment]
INFO on both...
@oncleben31 are you happy with this latest commit?

**Review by oncleben31 — APPROVED** [review]

**Pull request merged**
